framework:
    cache:
        # Redis
        prefix_seed: symfony_4_redis_cache
        app: cache.adapter.redis
        default_redis_provider: redis://%redis.host%:%redis.port%

          # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
          #app: cache.adapter.apcu

          # Namespaced pools use the above "app" backend by default
        #pools:
        #my.dedicated.cache: ~
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
                default_lifetime: 86400