#user
api_me:
    path: '/api/me'
    methods: ['GET','PUT']
    defaults:
        _controller: App\Controller\UserController::meAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'me'
        
home:
    path: '/home'
    defaults:
        _controller: App\Controller\UserController::index


login:
    path: '/login'
profile:
    path: '/profile'
admin:
    path: '/admin'
